export function initData() {
  // Зоны атаки и защиты
  const ZONES = ["head", "neck", "body", "belly", "legs"];

  const players = [
    {
      id: "krosh",
      name: "Krosh",
      avatar: "assets/img/characters/krosh.png",
      hpMax: 110,
      hp: 110,
      damage: 12,
      critChance: 0.15,
      critMultiplier: 1.6,
      weapon: "Carrot",
      wins: 0,
      losses: 0,
    },
    {
      id: "losyash",
      name: "Losyash",
      avatar: "assets/img/characters/losyash.png",
      hpMax: 130,
      hp: 130,
      damage: 10,
      critChance: 0.12,
      critMultiplier: 1.5,
      weapon: "Microphone",
      wins: 0,
      losses: 0,
    },
    {
      id: "nusha",
      name: "Nusha",
      avatar: "assets/img/characters/pork.png",
      hpMax: 95,
      hp: 95,
      damage: 14,
      critChance: 0.18,
      critMultiplier: 1.8,
      weapon: "Hooves",
      wins: 0,
      losses: 0,
    },
    {
      id: "yoj",
      name: "Yoj",
      avatar: "assets/img/characters/yoj.png",
      hpMax: 120,
      hp: 120,
      damage: 11,
      critChance: 0.14,
      critMultiplier: 1.6,
      weapon: "Quills",
      wins: 0,
      losses: 0,
    },
    {
      id: "sovunya",
      name: "Sovunya",
      avatar: "assets/img/characters/sovunya.png",
      hpMax: 115,
      hp: 115,
      damage: 10,
      critChance: 0.12,
      critMultiplier: 1.5,
      weapon: "Frying pan",
      wins: 0,
      losses: 0,
    },
    {
      id: "pin",
      name: "Pin",
      avatar: "assets/img/characters/pin.png",
      hpMax: 85,
      hp: 85,
      damage: 16,
      critChance: 0.2,
      critMultiplier: 2.0,
      weapon: "Wrench",
      wins: 0,
      losses: 0,
    },
    {
      id: "barash",
      name: "Barash",
      avatar: "assets/img/characters/barash.png",
      hpMax: 70,
      hp: 70,
      damage: 28,
      critChance: 0.25,
      critMultiplier: 2.2,
      weapon: "Feather pen",
      wins: 0,
      losses: 0,
    },
    {
      id: "bibi",
      name: "Bibi",
      avatar: "assets/img/characters/bibi.png",
      hpMax: 666,
      hp: 666,
      damage: 6.66,
      critChance: 0.0666,
      critMultiplier: 6.66,
      weapon: "M134 Minigun",
      wins: 0,
      losses: 0,
    },
  ];

  const enemies = [
    {
      id: "cuddles",
      name: "Cuddles",
      avatar: "assets/img/enemy/cuddles.png",
      hpMax: 80,
      hp: 80,
      damage: 7,
      attackCount: 2,
      blockCount: 1,
      critChance: 0.08,
      critMultiplier: 1.4,
    },
    {
      id: "flaky",
      name: "Flaky",
      avatar: "assets/img/enemy/flaky.png",
      hpMax: 140,
      hp: 140,
      damage: 11,
      attackCount: 1,
      blockCount: 3,
      critChance: 0.1,
      critMultiplier: 1.6,
    },
    {
      id: "giggles",
      name: "Giggles",
      avatar: "assets/img/enemy/giggles.webp",
      hpMax: 65,
      hp: 65,
      damage: 9,
      attackCount: 2,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "handy",
      name: "Handy",
      avatar: "assets/img/enemy/handy.png",
      hpMax: 110,
      hp: 110,
      damage: 14,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.12,
      critMultiplier: 1.7,
    },
    {
      id: "nutty",
      name: "Nutty",
      avatar: "assets/img/enemy/nutty.webp",
      hpMax: 100,
      hp: 100,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "petunia",
      name: "Petunia",
      avatar: "assets/img/enemy/petunia.webp",
      hpMax: 100,
      hp: 100,
      damage: 13,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.14,
      critMultiplier: 1.7,
    },
    {
      id: "toothy",
      name: "Toothy",
      avatar: "assets/img/enemy/toothy.png",
      hpMax: 120,
      hp: 120,
      damage: 12,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.12,
      critMultiplier: 1.6,
    },
    {
      id: "mole",
      name: "the Mole",
      avatar: "assets/img/enemy/the_mole.png",
      hpMax: 150,
      hp: 150,
      damage: 10,
      attackCount: 1,
      blockCount: 3,
      critChance: 0.1,
      critMultiplier: 1.5,
    },
    {
      id: "sniffles",
      name: "Sniffles",
      avatar: "assets/img/enemy/sniffles.webp",
      hpMax: 90,
      hp: 90,
      damage: 16,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.18,
      critMultiplier: 1.9,
    },
    {
      id: "liftyShifty",
      name: "Lifty & Shifty",
      avatar: "assets/img/enemy/lifty&shifty.png",
      hpMax: 100,
      hp: 100,
      damage: 10,
      attackCount: 2,
      blockCount: 2,
      critChance: 0.12,
      critMultiplier: 1.6,
    },
    {
      id: "lumpy",
      name: "Lumpy",
      avatar: "assets/img/enemy/lumpy.webp",
      hpMax: 160,
      hp: 160,
      damage: 13,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.1,
      critMultiplier: 1.5,
    },
    {
      id: "fliqpy",
      name: "Fliqpy",
      avatar: "assets/img/enemy/fliqpy.webp",
      hpMax: 150,
      hp: 150,
      damage: 18,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.15,
      critMultiplier: 2.0,
    },
  ];


  // Начальный игрок
  const player = players[0];

  return {
    ZONES,
    enemies,
    players,
    player,
    getRandomEnemy() {
      const randomIndex = Math.floor(Math.random() * enemies.length);
      return { ...enemies[randomIndex] };
    },
    resetEnemy(enemy) {
      enemy.hp = enemy.hpMax;
      return enemy;
    },
    getPlayerById(id) {
      return players.find((p) => p.id === id);
    },
  };
}
