export function initData() {
  // Зоны атаки и защиты
  const ZONES = ["head", "neck", "body", "belly", "legs"];

  // Пул противников
  const enemies = [
    {
      id: "cuddles",
      name: "Cuddles",
      avatar: "assets/img/enemy/cuddles.png",
      hpMax: 80,
      hp: 80,
      damage: 6,
      attackCount: 2,
      blockCount: 1,
      critChance: 0.05,
      critMultiplier: 1.5,
    },
    {
      id: "flaky",
      name: "Flaky",
      avatar: "assets/img/enemy/flaky.png",
      hpMax: 150,
      hp: 150,
      damage: 12,
      attackCount: 1,
      blockCount: 3,
      critChance: 0.08,
      critMultiplier: 1.25,
    },
    {
      id: "giggles",
      name: "Giggles",
      avatar: "assets/img/enemy/giggles.webp",
      hpMax: 60,
      hp: 60,
      damage: 8,
      attackCount: 1,
      blockCount: 2,
      critChance: 0.12,
      critMultiplier: 2.0,
    },
    {
      id: "handy",
      name: "Handy",
      avatar: "assets/img/enemy/handy.png",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "nutty",
      name: "Nutty",
      avatar: "assets/img/enemy/nutty.webp",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "petunia",
      name: "Petunia",
      avatar: "assets/img/enemy/petunia.webp",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "toothy",
      name: "Toothy",
      avatar: "assets/img/enemy/toothy.png",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "mole",
      name: "the Mole",
      avatar: "assets/img/enemy/the_mole.png",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "sniffles",
      name: "Sniffles",
      avatar: "assets/img/enemy/sniffles.webp",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "liftyShifty",
      name: "Lifty & Shifty",
      avatar: "assets/img/enemy/lifty&shifty.png",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "lumpy",
      name: "Lumpy",
      avatar: "assets/img/enemy/lumpy.webp",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
    {
      id: "fliqpy",
      name: "Fliqpy",
      avatar: "assets/img/enemy/fliqpy.webp",
      hpMax: 120,
      hp: 120,
      damage: 15,
      attackCount: 1,
      blockCount: 1,
      critChance: 0.15,
      critMultiplier: 1.8,
    },
  ];

  // Доступные персонажи для выбора
  const players = [
    {
      id: "krosh",
      name: "Krosh",
      avatar: "assets/img/characters/krosh.png",
      hpMax: 100,
      hp: 100,
      damage: 10,
      critChance: 0.1,
      critMultiplier: 1.5,
      wins: 0,
      losses: 0,
    },
    {
      id: "losyash",
      name: "Losyash",
      avatar: "assets/img/characters/losyash.png",
      hpMax: 100,
      hp: 100,
      damage: 10,
      critChance: 0.1,
      critMultiplier: 1.5,
      wins: 0,
      losses: 0,
    },
    {
      id: "nusha",
      name: "Nusha",
      avatar: "assets/img/characters/nusha.png",
      hpMax: 90,
      hp: 90,
      damage: 12,
      critChance: 0.15,
      critMultiplier: 1.8,
      wins: 0,
      losses: 0,
    },
    {
      id: "yoj",
      name: "Yoj",
      avatar: "assets/img/characters/yoj.png",
      hpMax: 100,
      hp: 100,
      damage: 10,
      critChance: 0.1,
      critMultiplier: 1.5,
      wins: 0,
      losses: 0,
    },
    {
      id: "sovunya",
      name: "Sovunya",
      avatar: "assets/img/characters/sovunya.png",
      hpMax: 100,
      hp: 100,
      damage: 10,
      critChance: 0.1,
      critMultiplier: 1.5,
      wins: 0,
      losses: 0,
    },
    {
      id: "pin",
      name: "Pin",
      avatar: "assets/img/characters/pin.png",
      hpMax: 80,
      hp: 80,
      damage: 15,
      critChance: 0.2,
      critMultiplier: 2.0,
      wins: 0,
      losses: 0,
    },
    {
      id: "barash",
      name: "Barash",
      avatar: "assets/img/characters/barash.png",
      hpMax: 60,
      hp: 60,
      damage: 30,
      critChance: 0.3,
      critMultiplier: 2.0,
      wins: 0,
      losses: 0,
    },
    {
      id: "bibi",
      name: "Bibi",
      avatar: "assets/img/characters/bibi.png",
      hpMax: 666,
      hp: 666,
      damage: 6.66,
      critChance: 0.0666,
      critMultiplier: 6.66,
      wins: 0,
      losses: 0,
    },
  ];

  // Начальный игрок
  const player = players[0];

  return {
    ZONES,
    enemies,
    players,
    player,
    getRandomEnemy() {
      const randomIndex = Math.floor(Math.random() * enemies.length);
      return { ...enemies[randomIndex] };
    },
    resetEnemy(enemy) {
      enemy.hp = enemy.hpMax;
      return enemy;
    },
    getPlayerById(id) {
      return players.find((p) => p.id === id);
    },
  };
}
